services:
  postgeres:
    image: postgres:17.4-alpine
    container_name: postgres_app
    restart: always
    environment:
      - POSTGRES_USER: user
      - POSTGRES_PASSWORD: password
      - POSTGRES_DATABASE: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'

  app:
    build:
    container_name: postgres_app
    restart: always
    depends_on:
      - postgres
    ports:
      - '4000:3001'
    environment:
      - DATABASE_URL: 'postgresql://user:password@postgres:5432/postgres'
    command: ['npm', 'run', 'start:prod']

volumes:
  pgdata: